name: CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'splice-api/**'
      - 'splice-service/**'
      - '.github/workflows/**'
  push:
    branches: [ main ]
    paths:
      - 'splice-api/**'
      - 'splice-service/**'
      - '.github/workflows/**'

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      splice-api: ${{ steps.filter.outputs.splice-api }}
      splice-service: ${{ steps.filter.outputs.splice-service }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          splice-api:
            - 'splice-api/**'
          splice-service:
            - 'splice-service/**'

  build-and-test-splice-api:
    name: Build and Test splice-api
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.splice-api == 'true' }}

    defaults:
      run:
        working-directory: ./splice-api

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install --frozen-lockfile

    - name: Build package
      run: bun run build

    - name: Verify build artifacts
      run: |
        ls -la dist/
        node -e "console.log('Package built successfully')"

  build-and-test-splice-service:
    name: Build and Test splice-service
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.splice-service == 'true' }}

    defaults:
      run:
        working-directory: ./splice-service

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install splice-api dependencies
      run: |
        cd ../splice-api
        bun install --frozen-lockfile
        bun run build

    - name: Install splice-service dependencies
      run: bun install --frozen-lockfile

    - name: Run linting
      run: bun run lint

    - name: Run type checking
      run: bunx tsc --noEmit

    - name: Run tests with coverage
      run: bun run test:cov
      env:
        API_STORE_ENCRYPTION_KEY: test-encryption-key-32-bytes-long

    - name: Build application
      run: bun run build
