name: ci

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-and-test-monorepo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - run: bun install --frozen-lockfile
    - run: bun run build
    - run: bun run lint
    - run: bun run test:cov
      env:
        API_STORE_ENCRYPTION_KEY: test-encryption-key-32-bytes-long
